name: SimbirSoft_test_for_SDET

on:
    workflow_dispatch:
        inputs:
            deployment_target: 
                description: Choosing the number of tests
                required: true
                default:
                type: choice
                options:
                    - All_tests
                    - Tests_by_xpath
                    - Tests_by_CSS
                    - Tests_by_ID

permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    test_run: 
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                python-version: "3.12.3"
            - name: Install Chrome
              run: sudo apt-get install google-chrome-stable
            - name: Install dependencies
              run: pip install -r requirements.txt
            - name: All_tests
              if: github.event.inputs.deployment_target == 'All_tests'
              run: pytest --alluredir=allure-results
              continue-on-error: true
            - name: Tests_by_xpath
              if: github.event.inputs.deployment_target == 'Tests_by_xpath'
              run: pytest tests/test_form_fields_by_xpath.py --alluredir=allure-results
              continue-on-error: true
            - name: Tests_by_CSS
              if: github.event.inputs.deployment_target == 'Tests_by_CSS'
              run: pytest tests/test_form_fields_by_css.py --alluredir=allure-results
              continue-on-error: true
            - name: Tests_by_ID
              if: github.event.inputs.deployment_target == 'Tests_by_ID'
              run: pytest tests/test_form_fields_by_id.py --alluredir=allure-results
              continue-on-error: true
            - name: Store allure results
              uses: actions/upload-artifact@v3   
              with:
                name: allure-results
                path: allure-results
                retention-days: 1    
    
    generate_report:
        runs-on: ubuntu-latest
        needs: test_run
        name: Generate Report 
        steps:
            - uses: actions/setup-java@v3   
              with:
                distribution: "microsoft"     
                java-version: "21"
            - run: sudo wget https://github.com/allure-framework/allure2/releases/download/2.28.1/allure-2.28.1.tgz && sudo tar -zxvf allure-2.28.1.tgz -C /opt/ && sudo ln -s /opt/allure-2.28.1/bin/allure /usr/bin/allure    
            - name: Download artifacts for allure
              uses: actions/download-artifact@v3
              with:
                name: allure-results
            - run: allure generate -c allure-results -o _site
            - name: Store report
              uses: actions/upload-artifact@v3   
              with:
                  name: _site
                  path: _site
                  retention-days: 1   
    
    publish_report:
        runs-on: ubuntu-latest
        needs: generate_report
        name: Publish Report 
        steps:
            - name: Download artifacts for allure
              uses: actions/download-artifact@v3
              with:
                name: _site
            - name: Upload Pages
              uses: actions/upload-pages-artifact@v2
              with:
                path: _site
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-page@v1.2.9
