name: SimbirSoft_test_for_SDET

on:
    workflow_dispatch:
        inputs:
            deployment_target: 
                description: Choosing the number of tests
                required: true
                default:
                type: choice
                options:
                    - All_tests
                    - Tests_by_xpath
                    - Tests_by_CSS
                    - Tests_by_ID


jobs:
    test_run: 
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            - name: setup Python
              uses: actions/setup-python@v4
              with:
                python-version: "3.12.3"
            - name: Install Chrome
              run: sudo apt-get install google-chrome-stable
            - name: install dependencies
              run: pip install -r requirements.txt
            - name: All_tests
              if: github.event.inputs.deployment_target == 'All_tests'
              run: pytest 
            - name: Tests_by_xpath
              if: github.event.inputs.deployment_target == 'Tests_by_xpath'
              run: pytest tests/test_form_fields_by_xpath.py
            - name: Tests_by_CSS
              if: github.event.inputs.deployment_target == 'Tests_by_CSS'
              run: pytest tests/test_form_fields_by_css.py
            - name: Tests_by_ID
              if: github.event.inputs.deployment_target == 'Tests_by_ID'
              run: pytest tests/test_form_fields_by_id.py
