name: SimbirSoft_test_for_SDET

on:
    push

jobs:
    test_run: 
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            - name: setup Python
              uses: actions/setup-python@v4
              with:
                python-version: "3.12.3"
            - name: Install Chrome
              run: sudo apt-get install google-chrome-stable
            - name: install dependencies
              run: pip install -r requirements.txt
            - name: Run tests
              run: pytest
